<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
                                <?$APPLICATION->IncludeComponent(
                                "bitrix:news.list",
                                "template1",
                                Array(
                                        "DISPLAY_DATE" => "Y", 
                                        "DISPLAY_NAME" => "Y", 
                                        "DISPLAY_PICTURE" => "N", 
                                        "DISPLAY_PREVIEW_TEXT" => "N", 
                                        "IBLOCK_TYPE" => "news", 
                                        "IBLOCK_ID" => "7", 
                                        "NEWS_COUNT" => "2", 
                                        "SORT_BY1" => "SORT", 
                                        "SORT_ORDER1" => "ASC", 
                                        "SORT_BY2" => "ACTIVE_FROM", 
                                        "SORT_ORDER2" => "DESC", 
                                        "FILTER_NAME" => "", 
                                        "FIELD_CODE" => Array("",""), 
                                        "PROPERTY_CODE" => Array("",""), 
                                        "DETAIL_URL" => "", 
                                        "PREVIEW_TRUNCATE_LEN" => "", 
                                        "ACTIVE_DATE_FORMAT" => "d.m.Y", 
                                        "DISPLAY_PANEL" => "N", 
                                        "SET_TITLE" => "N", 
                                        "INCLUDE_IBLOCK_INTO_CHAIN" => "N", 
                                        "ADD_SECTIONS_CHAIN" => "N", 
                                        "HIDE_LINK_WHEN_NO_DETAIL" => "N", 
                                        "PARENT_SECTION" => "", 
                                        "CACHE_TYPE" => "A", 
                                        "CACHE_TIME" => "3600", 
                                        "CACHE_FILTER" => "N", 
                                        "DISPLAY_TOP_PAGER" => "N", 
                                        "DISPLAY_BOTTOM_PAGER" => "N", 
                                        "PAGER_TITLE" => "Новости", 
                                        "PAGER_SHOW_ALWAYS" => "N", 
                                        "PAGER_TEMPLATE" => "", 
                                        "PAGER_DESC_NUMBERING" => "N", 
                                        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                                        "TITLE"=>"Новости компании"
                                )
                        );?>
<div class="rightSeparator"></div>
